### ISSUE TITLE
Cannot write new article due to validation

### ISSUE THREAD

**Issue by aj-foster** [orientation/orientation#127]
(On master) when beginning a new article, the view asks `!@article.valid?`. This triggers `before_validation :generate_slug`. However, the article's title may be `nil` at this point, so `Article#generate_slug` fails on `self.slug = title.parameterize`.

I believe the issue was introduced in a6ca8d3.

Not confident enough to fix myself and blind-side you with a pull request, but I am happy to implement a fix with guidance.

**Comment by olivierlacan** [comment]
Good catch. Found it the other day and it's very dumb. I'm going to kill two birds with one stone and replace the entire slug mechanism so that we archive previous slugs as well.

**Comment by SkyWDev** [comment]
I also ran into this error when trying to create a new article. Hope you fix it soon, I really want to try the app!
Bests

**Comment by olivierlacan** [comment]
@SkyWDev On it right now.

**Comment by SkyWDev** [comment]
Great!
Can't wait to try it

**Comment by olivierlacan** [comment]
@SkyWDev @aj-foster You too make sure to run `rake db:migrate` after pulling the latest master.

**Comment by olivierlacan** [comment]
Seems like the migration doesn't do what I want yet. Hold off.

**Comment by SkyWDev** [comment]
Some news @olivierlacan ?

**Comment by olivierlacan** [comment]
Traveling. This should be fixed. Can you verify for me?

**Comment by SkyWDev** [comment]
Yes, it is!

**Comment by olivierlacan** [comment]
Awesome!
