### ISSUE TITLE
Add FriendlyId to tags

### ISSUE THREAD

**Issue by olivierlacan** [orientation/orientation#139]
So that http://orientation.example.com/tags/91 becomes http://orientation.example.com/tags/foodies

**Comment by mattpolito** [comment]
@olivierlacan Is there a reason FriendlyId was chosen for handling slug functionality? Maybe a specific feature that it provides? It seems a bit heavy for how i'm seeing it used right now.

**Comment by mattpolito** [comment]
@olivierlacan This is done and merged. I'm not able to close though.

**Comment by olivierlacan** [comment]
Done, thanks!
