### ISSUE TITLE
Heroku Setup

### ISSUE THREAD

**Issue by jasonbahl** [orientation/orientation#140]
Per discussion here (https://github.com/orientation/orientation/issues/96#issuecomment-106026254) I've opened this new issue. 

I used the Heroku Button to deploy the app and I'm getting the "We're sorry, but something went wrong" screen when I try to login to the app. 

The error log says: `ERROR: relation "users" does not exist`

**Comment by olivierlacan** [comment]
@jasonbahl As I said in the previous thread, run `heroku run rake db:migrate`.

**Comment by olivierlacan** [comment]
@jasonbahl Can you follow up on this? I'll close it for now since I believe this should solve your problem.

**Comment by jasonbahl** [comment]
@olivierlacan - sorry for the delay. Was out for a few days. I just ran `heroku run rake db:migrate --app {{name of my app}}` and we're all good now. 

Thanks for the help!

**Comment by Potherca** [comment]
I could be wrong but I get the distinct impression this could be resolved to be automatic by adding the following to the `app.json`:

```
"scripts": {
    "postdeploy": "heroku run rake db:migrate"
  }
```
