### ISSUE TITLE
That add-on plan is only available to select users.

### ISSUE THREAD

**Issue by boetter** [orientation/orientation#144]
I get this error when trying to set up on Heroku using the button: "That add-on plan is only available to select users."

Any ideas on how to solve this?

**Comment by olivierlacan** [comment]
@boetter Which add-on plan is that. Do they say?

**Comment by rwdaigle** [comment]
@olivierlacan they don't say:

![](http://cl.ly/bqEW/Image%202015-07-01%20at%209.45.35%20AM.png)

**Comment by olivierlacan** [comment]
Since we have @craigkerstiens around, perhaps he knows. :kissing_cat:

**Comment by craigkerstiens** [comment]
I'm initially stumped but will poke around some and report back

**Comment by craigkerstiens** [comment]
Actually looks like heroku-postgresql has been updated to heroku-postgresql:hobby-dev

**Comment by olivierlacan** [comment]
@craigkerstiens Alright, I'll update it then. :-)

**Comment by rwdaigle** [comment]
Looks like the issue still exists even though the add-on plans look right?

![](http://cl.ly/bqGc/Image%202015-07-01%20at%2010.35.06%20AM.png)

![](http://cl.ly/bpdq/Image%202015-07-01%20at%2010.35.18%20AM.png)

**Comment by ansiqu** [comment]
alright,thanks your proposal @craigkerstiens

**Comment by olivierlacan** [comment]
@rwdaigle Sorry about that. I'll fix it in master right now.
