### ISSUE TITLE
Question about potential PR

### ISSUE THREAD

**Issue by fusion2004** [orientation/orientation#148]
I'm wondering if you would accept a PR for this commit: 
https://github.com/IZEA/orientation/commit/1c69bb12b5d53c86d3da4fe94a269e64e4e3d4de

The change itself seems fairly inconsequential, but I did this because the original code seemed to cause a crash in ruby somewhere in ActiveRecord. The error as seen in our heroku logs:
```
stderr: /app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/merger.rb:156:
stderr: [BUG]
stderr: Illegal instruction at 0x007f6e34951166
stderr:
stderr: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

I upgraded rails to the latest, as well as making this change, and I don't believe we've seen a crash since then.

**Comment by olivierlacan** [comment]
Actually I'd prefer killing the `unless` and using `if article.tags.present?` instead. I'd be game for a PR like that for sure.

**Comment by olivierlacan** [comment]
@fusion2004 Any news on this?
