### ISSUE TITLE
Perhaps Guides should not be allowed to go stale

### ISSUE THREAD

**Issue by olivierlacan** [orientation/orientation#149]
So, they're like Wonderbread.

**Comment by maxfindel** [comment]
Twinkie Guides :)

**Comment by olivierlacan** [comment]
For now I don't think I'm going to give special treatment to Guides unless someone comes up with a better argument for them not going stale.

They're content just as much as normal articles, and that content will go stale if humans don't come by every so often to update them, add new links to new articles, remove old links to old stale articles, etc.
