### ISSUE TITLE
google oauth question

### ISSUE THREAD

**Issue by erickorozco** [orientation/orientation#152]
Hello, 

I'm trying to install orientation on heroku, but I can't figure out what the GOOGLE_KEY and the GOOGLE_SECRET environment variables should I use. Right now, I'm using the client_id and the client secret. 

Thanks.

**Comment by olivierlacan** [comment]
This terminology might have changed but that sounds correct. Does it not work for you?

**Comment by boetter** [comment]
I am also having trouble here. I added client id as key and secret as secret in environment vars.

This brings up an oAuth login with google, but the redirect fails. I made sure to add MYAPP.herokuapp.com/auth/google_oauth2/callback as redirect uri when creating the client id. Any ideas? It seems to work fine for login, except it brings this message when done:

We're sorry, but something went wrong.

If you are the application owner check the logs for more information.

Not sure which logs to check, as I am on free Heroku.

**Comment by erickorozco** [comment]
Hi, 

thanks for your quick response, I read here: http://stackoverflow.com/questions/17166848/invalid-client-in-google-oauth2 that sometimes the client_id doesn't works, so I created a new one, along with a new heroku app and everything worked correctly! 

@boetter  I also got that error, in my case I had to run pending migrations. So run the following heroku run -a my-app-name rake db:migrate.

**Comment by boetter** [comment]
Thanks so much @erickorozco - running "heroku run -a my-app-name rake db:migrate" worked like a charm!

**Comment by brupm** [comment]
How does on limit logins to a specific domain? In other words, out of the box anyone can login with their google account (unless I am missing something).

**Comment by erickorozco** [comment]
There a guide that will allow you to restrict access to a certain domain, however I'm not sure if you have to transfer the domain to google to achieve this. This is the link for the guide: https://cloud.google.com/appengine/articles/auth?hl=en

**Comment by ckorhonen** [comment]
Thats for the old App Engine, now (or as of 2011) its no longer possible to set domain restrictions from the Google Developer Console.

The solution appears to be adding a line to the `omniauth.rb` file:

```
OmniAuth.config.logger = Rails.logger

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :google_oauth2, ENV['GOOGLE_KEY'], ENV['GOOGLE_SECRET'],
  {
    prompt: "select_account",
    image_aspect_ratio: "square",
    # we're displaying at 80 pixels, this is for high density ("Retina") displays
    image_size: 160,
    hd: "your domain.com"
  }
end
```

**Comment by boetter** [comment]
I get a constant loop on my Orientation setup now. Everytime I try to login it just redirects me back to Google after waiting for Heroku/Orientation for a few seconds. I didn't change anything on my Orientation installation, so what could have happened?

**Comment by olivierlacan** [comment]
You didn't add your company (or personal) email domain to Orientation's User model. Orientation works with a domain whitelist to prevent people who don't have a verified Google Apps account from signing in.

**Comment by olivierlacan** [comment]
Closing because this appears to have been resolved.
