### ISSUE TITLE
Can't log out in the Development environment

### ISSUE THREAD

**Issue by plicjo** [orientation/orientation#189]
The ApplicationController#current_user method prevents the user from being able to log out in the non-production environments.

I think the current implementation is clever for auto-logging-in the user in the development environment. The problem lies in the inability to log out.

**Comment by olivierlacan** [comment]
Hi, I'm curious what you need to sign out for? All of Orientation is authenticated, therefore there's currently not a single controller action that would be shown when signed out.

If you plan to make some pages unrestricted, then I suggest you submit a PR that adds some sort of session variable mechanism in development as an alternative for OAuth. I think that would be fine.

**Comment by plicjo** [comment]
Alright, that sounds legit to me, Olivier.

By the way, we talked for awhile at RailsConf this year.

Whether you remember or not, wassup! #smallworld
