### ISSUE TITLE
Potentially Dangerous Upstream Change to auth.

### ISSUE THREAD

**Issue by brupm** [orientation/orientation#205]
`|| ""` is very risk, if someone pulls down the upstream into their fork and forgets to set the `ORIENTATION_EMAIL_WHITELIST` their wiki would be open to anyone with a Google account.

https://github.com/orientation/orientation/blob/master/config/initializers/omniauth.rb#L10

**Comment by fusion2004** [comment]
@olivierlacan What do you think about changing the line to:
```ruby
    hd: ENV.fetch("ORIENTATION_EMAIL_WHITELIST")
```

**Comment by olivierlacan** [comment]
Thanks for that @brupm & @fusion2004.

**Comment by olivierlacan** [comment]
@brupm The upstream doesn't include an `.env` file so I don't think this is actually possible unless someone also replaces their .env with the .env.example.yml which I could admittedly change to not have the insecure default.

**Comment by brupm** [comment]
Changing .env.example.yml to not have a insecure default would be my advise

**Comment by olivierlacan** [comment]
The problem is that I can't predict what people's Google Auth domain will be which means the app is broken (won't let anyone sign in) by default. I'm not sure I'm okay with that.

**Comment by olivierlacan** [comment]
@brupm Let me know what you think of 633e52bb4efd89af8d940a5ca24243b0908a334d
