### ISSUE TITLE
Code blocks should not be altered by Emoji support

### ISSUE THREAD

**Issue by yaningzhu** [orientation/orientation#206]
The emoji replacement is taking precedence over code blocks. I don't think that is intended.

Example:

```
# This works fine
ocf:heartbeat:ip

# This one appears weird
`ocf:heartbeat:ip`
```

source: https://github.com/orientation/orientation/pull/135

**Comment by sarkis** [comment]
+1

**Comment by sarkis** [comment]
This PR should fix this issue: https://github.com/orientation/orientation/pull/213

**Comment by olivierlacan** [comment]
This issue is now resolved, I've reverted Emoji support for now, see https://github.com/orientation/orientation/commit/1ef2256329a9ed8122b633c139a98c91b1b13ca7 for details.

**Comment by sarkis** [comment]
@olivierlacan thank you!
