### ISSUE TITLE
html tags are not escaped

### ISSUE THREAD

**Issue by nsheridan** [orientation/orientation#217]
This allows for script execution
http://try.orientation.io/articles/embedded-javascript

And can also prevent a page rendering correctly:
http://try.orientation.io/articles/a-tag-broke-my-page

**Comment by olivierlacan** [comment]
Two thoughts:
- Orientation should only be open to trusted users (I know it's a cop-out)
- Do you think it's reasonable to escape all HTML tags from a documentation article?

**Comment by nsheridan** [comment]
Well, authenticated and authorized don't always mean trusted :smile: 

Given that orientation supports and encourages markdown I think it's entirely reasonable to disable html tags entirely. That said I cannot speak for everyone who uses Orientation. I didn't even realise HTML tags were supported at all until a stray unclosed script tag broke a colleague's article. I suspect most Orientation users are equally unaware of Orientation's HTML tag support.

**Comment by olivierlacan** [comment]
I agree. :smiley:

**Comment by olivierlacan** [comment]
@nsheridan Fixed:
- http://try.orientation.io/articles/a-tag-broke-my-page
- http://try.orientation.io/articles/embedded-javascript
