### ISSUE TITLE
Decide on uniform links?

### ISSUE THREAD

**Issue by adamfortuna** [orientation/orientation#82]
I've seen a number of different link formats for links within orientation articles, and was wondering if there was a suggested standard.

I'd love to just be able to say `(Installing Campus Courses)[installing-campus-courses]` and it could make it work. That'd also be pretty slick, because we could know that that's a slug and style the link differently if they page exists vs if it doesn't (which is a bit tougher if we give full URLs or relative URLs).

Any thoughts on a suggested standard?

**Comment by olivierlacan** [comment]
Tadaaa: https://github.com/orientation/orientation/blob/master/NEWS.md#september-15th-2015 :tophat:
