### ISSUE TITLE
Can't add a shorter tag when one containing the same first word exists

### ISSUE THREAD

**Issue by olivierlacan** [orientation/orientation#9]
![](http://f.cl.ly/items/0o1d203c0i2L3M2D390K/Screen%20Shot%202013-03-12%20at%2012.26.42%20PM.png)

Bit of a bummer.

**Comment by josler** [comment]
Hey @olivierlacan can we look at reopening this? It's a bit of a pain to not be able to create smaller tags - say "Username" vs "User".

**Comment by olivierlacan** [comment]
Yep. Go for it. It's dumb. :-)
