### ISSUE TITLE
Orientation not allowing authentication

### ISSUE THREAD

**Issue by bijanbwb** [orientation/orientation#96]
Can't seem to get into Orientation. I tried both Chrome and Firefox and still get a 500 error.

**Comment by jasonbahl** [comment]
I just tried deploying to Heroku and I'm seeing this screen as well. What was the fix?

**Comment by olivierlacan** [comment]
@jasonbahl Not sure, check your server output with `heroku logs`.

**Comment by jasonbahl** [comment]
it's telling me `ERROR: relation "users" does not exist`

Possibly something went wrong with the deploy?

**Comment by jasonbahl** [comment]
@olivierlacan don't worry about troubleshooting if I'm the only one reporting issues. I'll assume it's something I screwed up on my end. Thanks for the quick reply though.

**Comment by olivierlacan** [comment]
@jasonbahl That's fine, you likely forgot to run `heroku run rake db:migrate`. Did you use the Heroku button or set it up on your own on Heroku?

**Comment by olivierlacan** [comment]
@jasonbahl Can you open a new issue, this one is wholly unrelated. Name it "Heroku Setup" if you want.
